### ISSUE TITLE
segfaults on linux-64

### ISSUE THREAD

**Issue by benmoss** [conda-forge/x13as-feedstock#1]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Just tried 1.1.61 hba6bba4_0 on a linux/amd64 machine and am getting a segmentation fault when I call either binary

### Installed packages

```
matplotlib   3.9.2    py312h7900ff3_1  8.6 KiB   conda  matplotlib-3.9.2-py312h7900ff3_1.conda
pandas       2.2.3    py312hf9745cd_1  14.7 MiB  conda  pandas-2.2.3-py312hf9745cd_1.conda
statsmodels  0.14.4   py312hc0a28a1_0  11.5 MiB  conda  statsmodels-0.14.4-py312hc0a28a1_0.conda
x13as        1.1.61   hba6bba4_0       3.1 MiB   conda  x13as-1.1.61-hba6bba4_0.conda
```

### Environment info

```
      Pixi version: 0.32.1
          Platform: linux-64
  Virtual packages: __unix=0=0
                  : __linux=5.15.0=0
                  : __glibc=2.35=0
                  : __archspec=1=broadwell
         Cache dir: /home/bmoss40/.cache/rattler/cache
      Auth storage: /home/bmoss40/.rattler/credentials.json
  Config locations: No config files found

Project
------------
              Name: x13as
           Version: 0.1.0
     Manifest file: /home/bmoss40/x13as/pixi.toml
      Last updated: 14-10-2024 12:32:52

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge
  Dependency count: 4
      Dependencies: x13as, statsmodels, matplotlib, pandas
  Target platforms: linux-64
```

**Comment by benmoss** [comment]
Repro:

```
$ mkdir /tmp/x13
$ cd $_
$ pixi init
✔ Created /tmp/x13/pixi.toml
$ pixi add x13as
✔ Added x13as >=1.1.61,<2
$ pixi shell
 . "/tmp/pixi_env_K8C.sh"
$  . "/tmp/pixi_env_K8C.sh"
$ which x13as_html
/tmp/x13/.pixi/envs/default/bin/x13as_html
$ x13as_html
Segmentation fault (core dumped)
```

**Comment by benmoss** [comment]
Or with micromamba 

```
$ micromamba create -n x13 x13as -c conda-forge
$ micromamba run -n x13 x13as_html
$ echo $?
139
```

**Comment by jjerphan** [comment]
I can reproduce the segfault on Linux.

Using `gdb`, one can see that program fails at its real start (i.e. at `MAIN__`).

**Comment by h-vetinari** [comment]
That _might_ just be a bug in x13as itself -- i.e. the case where no argument are provided isn't handled.

During the bring-up in https://github.com/conda-forge/staged-recipes/pull/27853, I tried both `x13as_{ascii,html} --help` and `x13as_{ascii,html} -I`. Both fail (the first because `--help` is not recognized, the second because `-I` needs an argument), but didn't segfault and actually returned an exit code of 0.

Since there's no easily discoverable command line reference, I don't know how to write a test for this. If you have one, please let me know.

**Comment by jjerphan** [comment]
`x13as_{ascii,html} --help` and `x13as_{ascii,html} -I` segfault on my machine.

Could it be due to slight differences related to [the core dependencies](https://conda-forge.org/docs/maintainer/knowledge_base/#core-dependency-tree-packages-cdts)?

```
       libmamba version : 2.0.2
     micromamba version : 2.0.2
           curl version : libcurl/8.9.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : $HOME/.local/miniforge3/envs
          package cache : $HOME/.cache/conda/pkgs
            environment : gh-1844 (active)
           env location : $HOME/.local/miniforge3/envs/gh-1844
      user config files : $HOME/.mambarc
 populated config files : $HOME/.condarc
       virtual packages : __unix=0=0
                          __linux=6.10.12=0
                          __glibc=2.39=0
                          __archspec=1=x86_64_v3
                          __cuda=12.6=0
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : $HOME/.local/miniforge3
               platform : linux-64
```

**Comment by h-vetinari** [comment]
> Could it be due to slight differences related to [the core dependencies](https://conda-forge.org/docs/maintainer/knowledge_base/#core-dependency-tree-packages-cdts)?

That's pretty unlikely, because we're not using any here. The only thing we're using is the sysroot. Could you try to build the recipe locally but with
```diff
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -25,6 +25,7 @@ build:

 requirements:
   build:
-    - {{ stdlib("c") }}
+    - sysroot_linux-64 2.28
     - {{ compiler("fortran") }}
     - make      # [unix]
```
And see if that changes anything? Unfortunately we don't have a newer sysroot packaged yet; you could also try to build against your own machine by not using the compiler activation (though this would need some care with playing around with FFLAGS / LDFLAGS).

**Comment by benmoss** [comment]
I'm getting `sysroot_linux-64 2.17.*,2.28.*  does not exist (perhaps a typo or a missing channel).`. 

I'm not able to use `build_locally.py` so I'm not sure if I'm not building in a valid way but I'm just running `conda build ./recipe/ -m ./.ci_support/linux_64_.yaml`. It segfaulted in the test phase when I ran it without the sysroot patch.

**Comment by h-vetinari** [comment]
> I'm getting `sysroot_linux-64 2.17.*,2.28.* does not exist (perhaps a typo or a missing channel).`.

I think you're getting a conflict between two different sysroots; I've updated the patch above, please try that one.

> I'm not sure if I'm not building in a valid way but I'm just running `conda build ./recipe/ -m ./.ci_support/linux_64_.yaml`.

That sounds good

**Comment by benmoss** [comment]
That still segfaults on the test

```
+ x13as_ascii -I
/home/bmoss40/x13as-feedstock/.pixi/envs/default/conda-bld/x13as_1729094283410/test_tmp/run_test.sh: line 7: 3562476 Segmentation fault      (core dumped) x13as_ascii -I
WARNING: Tests failed for x13as-1.1.61-h88e632e_0.tar.bz2 - moving package to /home/bmoss40/x13as-feedstock/.pixi/envs/default/conda-bld/broken

CondaBuildUserError: TESTS FAILED: x13as-1.1.61-h88e632e_0.tar.bz2
```

**Comment by jjerphan** [comment]
Locally I can reproduce the failure with a slightly more informative message:

```
+ x13as_ascii -I
x13as_ascii: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory
```

**Comment by jjerphan** [comment]
As of 742849408f0c2352c403ac3b793921f4209c4bea, I can reproduce the segfault:

```
+ x13as_ascii -I
/home/conda/feedstock_root/build_artifacts/x13as_1729185344954/test_tmp/run_test.sh: line 7:  5002 Segmentation fault      (core dumped) x13as_ascii -I
```

With the patch given in https://github.com/conda-forge/x13as-feedstock/issues/1#issuecomment-2413254426, I can locally reproduce the failure with a slightly more informative message:

```
+ x13as_ascii -I
x13as_ascii: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory
```

On the associated built binaries, I get
```
ldd x13as_ascii                                     
```
```
        linux-vdso.so.1 (0x00007fa49ddf9000)
        libgfortran.so.5 => /lib64/libgfortran.so.5 (0x00007fa488000000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fa48831c000)
        libmvec.so.1 => /lib64/libmvec.so.1 (0x00007fa487f06000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa487ed8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fa487ce7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa49ddfb000)
```

```
ldd x13as_html 
```
```
        linux-vdso.so.1 (0x00007fb986f7b000)
        libgfortran.so.5 => /lib64/libgfortran.so.5 (0x00007fb971000000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb97131c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb986f2b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb970e0f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb986f7d000)
```

**Comment by jjerphan** [comment]
Locally on the associated built binaries, I get
```
ldd x13as_ascii                                     
```
```
        linux-vdso.so.1 (0x00007fa49ddf9000)
        libgfortran.so.5 => /lib64/libgfortran.so.5 (0x00007fa488000000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fa48831c000)
        libmvec.so.1 => /lib64/libmvec.so.1 (0x00007fa487f06000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fa487ed8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fa487ce7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa49ddfb000)
```

```
ldd x13as_html 
```
```
        linux-vdso.so.1 (0x00007fb986f7b000)
        libgfortran.so.5 => /lib64/libgfortran.so.5 (0x00007fb971000000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb97131c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb986f2b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb970e0f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb986f7d000)
```

**Comment by h-vetinari** [comment]
> `x13as_ascii: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory`

Thanks for digging this up! I've never heard about that library, but it's in the sysroot (for 2.28, _not_ 2.17), and by the name it's presumably a component/dependency of `libm.so`. We could try re-adding `-static` on linux (effectively a partial revert of https://github.com/conda-forge/staged-recipes/commit/05e8942d987fd17accd05bfbb47d2140154e56d7) so that the builds don't need to look for `libm` and friends, but it's still surprising to me that this fails in the first place.

CC @conda-forge/linux-sysroot @xhochy

**Comment by benmoss** [comment]
Re-adding `-static` gets me 

> $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran -static -o x13as_ascii <all the .o files>   -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -lm
/home/bmoss40/x13as-feedstock/.pixi/envs/default/conda-bld/x13as_1729210279928/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lquadmath: No such file or directory

`$PREFIX/lib` does have `libquadmath.so`, so not sure what the problem would be

**Comment by jjerphan** [comment]
> `$PREFIX/lib` does have `libquadmath.so`, so not sure what the problem would be

`libquadmath.so` is a shared library which a priori won't be picked if we choose static linkage.

Builds of `libgcc-ng` and `libgcc` only distribute:

```
 ./lib/libquadmath.so.0
 ./lib/libquadmath.so.0.0.0
 ./lib/libquadmath.so
 ./share/info/libquadmath.info
```

I am exploring the issue with #2. To me dynamic linking should be used, and we need to understand how [`libmvec` integrated in `glibc 2.22`](https://sourceware.org/glibc/wiki/libmvec) can be resolved.

`glibc 2.17` is used on the feedstock to build the project, but 2.17 does not yet incorporate `libmvec` which apparently this project depends on (the fact that #2 passes on the CI but fails locally is surprising).

We could statically link mathematical libraries of `glibc` (with indications given for `libmvec`) only and keep dynamic linkage for all the other libraries.

**Comment by isuruf** [comment]
This is a bug with gfortran 9 and building with gfortran>=10 should fix the bug.

**Comment by jjerphan** [comment]
Do you have a reference so that we can understand and resolve the problem? :)

Currently using `gfortran>=10` for Unix makes the compilation fail locally.

**Comment by h-vetinari** [comment]
> Currently using `gfortran>=10` for Unix makes the compilation fail locally.

The upstream sources would need to be fixed for use of gfortran>=10 (or perhaps some default changed where we can opt back into the old behaviour...?). Runs [into](https://github.com/conda-forge/staged-recipes/pull/27853#issuecomment-2408445374)

```
$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran -O2  -c -o adpdrg.o adpdrg.f
adpdrg.f:409:72:

  409 |      &               'after end of LS sequence (LSS)',T)
      |                                                                        1
Error: More actual than formal arguments in procedure call at (1)
```

**Comment by h-vetinari** [comment]
I managed to unpin gfortran in #3. Thanks for the input @isuruf, let's hope that this fixes things indeed 🤞 

Like @jjerphan asked, I'd also appreciate some references or background on this, if you have some. :)
